export type ProgramDifficulty = 1 | 2 | 3; // 1: 初級, 2: 中級, 3: 上級

export interface WorkoutProgram {
  id: string;
  title: string;
  durationMin: number;
  exerciseCount: number;
  difficulty: ProgramDifficulty;
  targetArea: string;
  exercises?: { exercise: string, duration?: string, reps?: string }[];
}

export const WORKOUT_PROGRAMS: Record<string, WorkoutProgram[]> = {
  '腹筋': [
    { id: 'abs-1', title: '腹筋 初級', durationMin: 15, exerciseCount: 16, difficulty: 1, targetArea: '腹筋', exercises: [{"exercise":"ジャンピングジャック","duration":"00:30"},{"exercise":"クランチ","reps":"x15"},{"exercise":"ロシアン・ツイスト","reps":"x20"},{"exercise":"マウンテンクライマー","duration":"00:20"},{"exercise":"レッグレイズ","reps":"x15"},{"exercise":"プランク","duration":"00:30"},{"exercise":"クランチ","reps":"x15"},{"exercise":"バイシクルクランチ","reps":"x20"},{"exercise":"マウンテンクライマー","duration":"00:20"},{"exercise":"シザーズ","duration":"00:20"},{"exercise":"レッグレイズ","reps":"x15"},{"exercise":"プランク","duration":"00:30"},{"exercise":"ストレッチ","duration":"00:30"}] },
    { id: 'abs-2', title: '腹筋 中級', durationMin: 24, exerciseCount: 20, difficulty: 2, targetArea: '腹筋', exercises: [{"exercise":"ジャンピングジャック","duration":"00:40"},{"exercise":"クランチ","reps":"x20"},{"exercise":"ロシアン・ツイスト","reps":"x30"},{"exercise":"マウンテンクライマー","duration":"00:30"},{"exercise":"レッグレイズ","reps":"x20"},{"exercise":"バイシクルクランチ","reps":"x30"},{"exercise":"プランク","duration":"00:45"},{"exercise":"クランチ","reps":"x20"},{"exercise":"ロシアン・ツイスト","reps":"x30"},{"exercise":"マウンテンクライマー","duration":"00:30"},{"exercise":"シザーズ","duration":"00:30"},{"exercise":"レッグレイズ","reps":"x20"},{"exercise":"プランク","duration":"00:45"},{"exercise":"ストレッチ","duration":"00:30"}] },
    { id: 'abs-3', title: '腹筋 上級', durationMin: 30, exerciseCount: 24, difficulty: 3, targetArea: '腹筋', exercises: [{"exercise":"ジャンピングジャック","duration":"00:60"},{"exercise":"クランチ","reps":"x30"},{"exercise":"ロシアン・ツイスト","reps":"x40"},{"exercise":"マウンテンクライマー","duration":"00:45"},{"exercise":"レッグレイズ","reps":"x30"},{"exercise":"バイシクルクランチ","reps":"x40"},{"exercise":"シザーズ","duration":"00:45"},{"exercise":"プランク","duration":"01:00"},{"exercise":"クランチ","reps":"x30"},{"exercise":"ロシアン・ツイスト","reps":"x40"},{"exercise":"マウンテンクライマー","duration":"00:45"},{"exercise":"レッグレイズ","reps":"x30"},{"exercise":"プランク","duration":"01:00"},{"exercise":"ストレッチ","duration":"00:30"}] }
  ],
  '腕': [
    { id: 'arm-1', title: '腕 初級', durationMin: 15, exerciseCount: 15, difficulty: 1, targetArea: '腕', exercises: [{"exercise":"プッシュアップ","reps":"x10"},{"exercise":"ベンチディップス","reps":"x10"},{"exercise":"プランク","duration":"00:30"},{"exercise":"ダイアモンドプッシュアップ","reps":"x8"},{"exercise":"プッシュアップ","reps":"x10"},{"exercise":"ベンチディップス","reps":"x10"},{"exercise":"プランク","duration":"00:30"},{"exercise":"ダイアモンドプッシュアップ","reps":"x8"},{"exercise":"ストレッチ","duration":"00:30"}] },
    { id: 'arm-2', title: '腕 中級', durationMin: 22, exerciseCount: 20, difficulty: 2, targetArea: '腕', exercises: [{"exercise":"プッシュアップ","reps":"x15"},{"exercise":"ベンチディップス","reps":"x15"},{"exercise":"プランク","duration":"00:45"},{"exercise":"ダイアモンドプッシュアップ","reps":"x12"},{"exercise":"プッシュアップ","reps":"x15"},{"exercise":"ベンチディップス","reps":"x15"},{"exercise":"プランク","duration":"00:45"},{"exercise":"ダイアモンドプッシュアップ","reps":"x12"},{"exercise":"プッシュアップ","reps":"x15"},{"exercise":"ベンチディップス","reps":"x15"},{"exercise":"ストレッチ","duration":"00:30"}] },
    { id: 'arm-3', title: '腕 上級', durationMin: 30, exerciseCount: 25, difficulty: 3, targetArea: '腕', exercises: [{"exercise":"プッシュアップ","reps":"x20"},{"exercise":"ベンチディップス","reps":"x20"},{"exercise":"プランク","duration":"01:00"},{"exercise":"ダイアモンドプッシュアップ","reps":"x15"},{"exercise":"プッシュアップ","reps":"x20"},{"exercise":"ベンチディップス","reps":"x20"},{"exercise":"プランク","duration":"01:00"},{"exercise":"ダイアモンドプッシュアップ","reps":"x15"},{"exercise":"プッシュアップ","reps":"x20"},{"exercise":"ベンチディップス","reps":"x20"},{"exercise":"ストレッチ","duration":"00:30"}] }
  ],
  '胸部': [
    { id: 'chest-1', title: '胸部 初級', durationMin: 15, exerciseCount: 15, difficulty: 1, targetArea: '胸', exercises: [{"exercise":"ジャンピングジャック","duration":"00:30"},{"exercise":"プッシュアップ","reps":"x10"},{"exercise":"ダイアモンドプッシュアップ","reps":"x8"},{"exercise":"ベンチディップス","reps":"x10"},{"exercise":"プッシュアップ","reps":"x10"},{"exercise":"ダイアモンドプッシュアップ","reps":"x8"},{"exercise":"ベンチディップス","reps":"x10"},{"exercise":"ストレッチ","duration":"00:30"}] },
    { id: 'chest-2', title: '胸部 中級', durationMin: 22, exerciseCount: 20, difficulty: 2, targetArea: '胸', exercises: [{"exercise":"ジャンピングジャック","duration":"00:40"},{"exercise":"プッシュアップ","reps":"x15"},{"exercise":"ダイアモンドプッシュアップ","reps":"x12"},{"exercise":"パイクプッシュアップ","reps":"x10"},{"exercise":"ベンチディップス","reps":"x15"},{"exercise":"プッシュアップ","reps":"x15"},{"exercise":"ダイアモンドプッシュアップ","reps":"x12"},{"exercise":"パイクプッシュアップ","reps":"x10"},{"exercise":"ベンチディップス","reps":"x15"},{"exercise":"ストレッチ","duration":"00:30"}] },
    { id: 'chest-3', title: '胸部 上級', durationMin: 30, exerciseCount: 25, difficulty: 3, targetArea: '胸', exercises: [{"exercise":"バーピー","duration":"00:45"},{"exercise":"プッシュアップ","reps":"x20"},{"exercise":"ダイアモンドプッシュアップ","reps":"x15"},{"exercise":"パイクプッシュアップ","reps":"x15"},{"exercise":"ベンチディップス","reps":"x20"},{"exercise":"プッシュアップ","reps":"x20"},{"exercise":"ダイアモンドプッシュアップ","reps":"x15"},{"exercise":"パイクプッシュアップ","reps":"x15"},{"exercise":"ベンチディップス","reps":"x20"},{"exercise":"ストレッチ","duration":"00:30"}] }
  ],
  '脚': [
    { id: 'leg-1', title: '脚 初級', durationMin: 15, exerciseCount: 15, difficulty: 1, targetArea: '脚', exercises: [{"exercise":"ジャンピングジャック","duration":"00:30"},{"exercise":"スクワット","reps":"x15"},{"exercise":"ランジ","reps":"x12"},{"exercise":"ヒップブリッジ","reps":"x15"},{"exercise":"カーフレイズ","reps":"x20"},{"exercise":"スクワット","reps":"x15"},{"exercise":"ランジ","reps":"x12"},{"exercise":"ヒップブリッジ","reps":"x15"},{"exercise":"ストレッチ","duration":"00:30"}] },
    { id: 'leg-2', title: '脚 中級', durationMin: 25, exerciseCount: 20, difficulty: 2, targetArea: '脚', exercises: [{"exercise":"ジャンピングジャック","duration":"00:45"},{"exercise":"スクワット","reps":"x20"},{"exercise":"ランジ","reps":"x20"},{"exercise":"ヒップブリッジ","reps":"x20"},{"exercise":"カーフレイズ","reps":"x30"},{"exercise":"スクワット","reps":"x20"},{"exercise":"ランジ","reps":"x20"},{"exercise":"ヒップブリッジ","reps":"x20"},{"exercise":"カーフレイズ","reps":"x30"},{"exercise":"ストレッチ","duration":"00:30"}] },
    { id: 'leg-3', title: '脚 上級', durationMin: 35, exerciseCount: 25, difficulty: 3, targetArea: '脚', exercises: [{"exercise":"ジャンピングジャック","duration":"01:00"},{"exercise":"スクワット","reps":"x30"},{"exercise":"ランジ","reps":"x30"},{"exercise":"ヒップブリッジ","reps":"x30"},{"exercise":"カーフレイズ","reps":"x40"},{"exercise":"スクワット","reps":"x30"},{"exercise":"ランジ","reps":"x30"},{"exercise":"ヒップブリッジ","reps":"x30"},{"exercise":"カーフレイズ","reps":"x40"},{"exercise":"ストレッチ","duration":"00:30"}] }
  ],
  '肩と背中': [
    { id: 'shoulder-back-1', title: '肩と背中 初級', durationMin: 15, exerciseCount: 15, difficulty: 1, targetArea: '肩', exercises: [{"exercise":"ジャンピングジャック","duration":"00:30"},{"exercise":"パイクプッシュアップ","reps":"x8"},{"exercise":"スーパーマン","reps":"x10"},{"exercise":"バックエクステンション","reps":"x10"},{"exercise":"プランク","duration":"00:30"},{"exercise":"パイクプッシュアップ","reps":"x8"},{"exercise":"スーパーマン","reps":"x10"},{"exercise":"バックエクステンション","reps":"x10"},{"exercise":"ストレッチ","duration":"00:30"}] },
    { id: 'shoulder-back-2', title: '肩と背中 中級', durationMin: 25, exerciseCount: 20, difficulty: 2, targetArea: '肩', exercises: [{"exercise":"ジャンピングジャック","duration":"00:45"},{"exercise":"パイクプッシュアップ","reps":"x12"},{"exercise":"スーパーマン","reps":"x15"},{"exercise":"バックエクステンション","reps":"x15"},{"exercise":"プランク","duration":"00:45"},{"exercise":"パイクプッシュアップ","reps":"x12"},{"exercise":"スーパーマン","reps":"x15"},{"exercise":"バックエクステンション","reps":"x15"},{"exercise":"ストレッチ","duration":"00:30"}] },
    { id: 'shoulder-back-3', title: '肩と背中 上級', durationMin: 35, exerciseCount: 25, difficulty: 3, targetArea: '肩', exercises: [{"exercise":"バーピー","duration":"00:45"},{"exercise":"パイクプッシュアップ","reps":"x15"},{"exercise":"スーパーマン","reps":"x20"},{"exercise":"バックエクステンション","reps":"x20"},{"exercise":"プランク","duration":"01:00"},{"exercise":"パイクプッシュアップ","reps":"x15"},{"exercise":"スーパーマン","reps":"x20"},{"exercise":"バックエクステンション","reps":"x20"},{"exercise":"ストレッチ","duration":"00:30"}] }
  ]
};
