export type ProgramDifficulty = 1 | 2 | 3; // 1: 初級, 2: 中級, 3: 上級

export interface WorkoutProgram {
  id: string;
  title: string;
  durationMin: number;
  exerciseCount: number;
  difficulty: ProgramDifficulty;
  targetArea: string;
  exercises?: { exercise: string, duration?: string, reps?: string }[];
}

export const WORKOUT_PROGRAMS: Record<string, WorkoutProgram[]> = {
  '腹筋': [
    { id: 'abs-1', title: '腹筋 初級', durationMin: 15, exerciseCount: 16, difficulty: 1, targetArea: '腹筋', exercises: [{"exercise":"ジャンピングジャック","duration":"00:20"},{"exercise":"アブドミナル・クランチ","reps":"x16"},{"exercise":"ロシアン・ツイスト","reps":"x20"},{"exercise":"マウンテン・クライマー","reps":"x16"},{"exercise":"ヒール・タッチ","reps":"x20"},{"exercise":"レッグレイズ","reps":"x16"},{"exercise":"プランク","duration":"00:20"},{"exercise":"アブドミナル・クランチ","reps":"x12"},{"exercise":"ロシアン・ツイスト","reps":"x32"},{"exercise":"マウンテン・クライマー","reps":"x12"},{"exercise":"ヒール・タッチ","reps":"x20"},{"exercise":"レッグレイズ","reps":"x14"},{"exercise":"プランク","duration":"00:30"},{"exercise":"コブラストレッチ","duration":"00:30"},{"exercise":"脊柱腰椎ひねりストレッチ（左）","duration":"00:30"},{"exercise":"脊柱腰椎ひねりストレッチ（右）","duration":"00:30"}] },
    { id: 'abs-2', title: '腹筋 中級', durationMin: 24, exerciseCount: 21, difficulty: 2, targetArea: '腹筋', exercises: [{"exercise":"ジャンピングジャック","duration":"00:30"},{"exercise":"アブドミナル・クランチ","reps":"x20"},{"exercise":"ロシアン・ツイスト","reps":"x24"},{"exercise":"マウンテン・クライマー","reps":"x20"},{"exercise":"ヒール・タッチ","reps":"x24"},{"exercise":"レッグレイズ","reps":"x20"},{"exercise":"プランク","duration":"00:30"},{"exercise":"V字腹筋","reps":"x16"},{"exercise":"バイシクルクランチ","reps":"x24"},{"exercise":"アブドミナル・クランチ","reps":"x20"},{"exercise":"ロシアン・ツイスト","reps":"x24"},{"exercise":"マウンテン・クライマー","reps":"x20"},{"exercise":"ヒール・タッチ","reps":"x24"},{"exercise":"レッグレイズ","reps":"x20"},{"exercise":"プランク","duration":"00:40"},{"exercise":"V字腹筋","reps":"x16"},{"exercise":"バイシクルクランチ","reps":"x24"},{"exercise":"プランク・ツイスト","reps":"x20"},{"exercise":"コブラストレッチ","duration":"00:30"},{"exercise":"脊柱腰椎ひねりストレッチ（左）","duration":"00:30"},{"exercise":"脊柱腰椎ひねりストレッチ（右）","duration":"00:30"}] },
    { id: 'abs-3', title: '腹筋 上級', durationMin: 27, exerciseCount: 21, difficulty: 3, targetArea: '腹筋', exercises: [{"exercise":"ジャンピングジャック","duration":"00:40"},{"exercise":"アブドミナル・クランチ","reps":"x24"},{"exercise":"ロシアン・ツイスト","reps":"x32"},{"exercise":"マウンテン・クライマー","reps":"x30"},{"exercise":"ヒール・タッチ","reps":"x30"},{"exercise":"レッグレイズ","reps":"x24"},{"exercise":"プランク","duration":"00:45"},{"exercise":"V字腹筋","reps":"x20"},{"exercise":"バイシクルクランチ","reps":"x30"},{"exercise":"プランク・ジャック","duration":"00:30"},{"exercise":"アブドミナル・クランチ","reps":"x24"},{"exercise":"ロシアン・ツイスト","reps":"x32"},{"exercise":"マウンテン・クライマー","reps":"x30"},{"exercise":"ヒール・タッチ","reps":"x30"},{"exercise":"レッグレイズ","reps":"x24"},{"exercise":"プランク","duration":"01:00"},{"exercise":"V字腹筋","reps":"x20"},{"exercise":"バイシクルクランチ","reps":"x30"},{"exercise":"コブラストレッチ","duration":"00:30"},{"exercise":"脊柱腰椎ひねりストレッチ（左）","duration":"00:30"},{"exercise":"脊柱腰椎ひねりストレッチ（右）","duration":"00:30"}] }
  ],
  '腕': [
    { id: 'arm-1', title: '腕 初級', durationMin: 16, exerciseCount: 19, difficulty: 1, targetArea: '腕', exercises: [{"exercise":"アームレイズ","duration":"00:30"},{"exercise":"サイドアームレイズ","duration":"00:30"},{"exercise":"三頭筋ディップ","reps":"x10"},{"exercise":"アームサークル（時計回り）","duration":"00:30"},{"exercise":"アームサークル（反時計回り）","duration":"00:30"},{"exercise":"ダイヤモンド・プッシュアップ","reps":"x8"},{"exercise":"プッシュアップ","reps":"x10"},{"exercise":"パンチ","duration":"00:30"},{"exercise":"アームレイズ","duration":"00:30"},{"exercise":"サイドアームレイズ","duration":"00:30"},{"exercise":"三頭筋ディップ","reps":"x10"},{"exercise":"アームサークル（時計回り）","duration":"00:30"},{"exercise":"アームサークル（反時計回り）","duration":"00:30"},{"exercise":"ダイヤモンド・プッシュアップ","reps":"x8"},{"exercise":"プッシュアップ","reps":"x10"},{"exercise":"パンチ","duration":"00:30"},{"exercise":"アームレイズ","duration":"00:30"},{"exercise":"肩のストレッチ","duration":"00:30"},{"exercise":"コブラストレッチ","duration":"00:30"}] },
    { id: 'arm-2', title: '腕 中級', durationMin: 22, exerciseCount: 25, difficulty: 2, targetArea: '腕', exercises: [{"exercise":"アームレイズ","duration":"00:33"},{"exercise":"サイドアームレイズ","duration":"00:33"},{"exercise":"三頭筋ディップ","reps":"x13"},{"exercise":"アームサークル（時計回り）","duration":"00:33"},{"exercise":"アームサークル（反時計回り）","duration":"00:33"},{"exercise":"ダイヤモンド・プッシュアップ","reps":"x10"},{"exercise":"プッシュアップ","reps":"x13"},{"exercise":"パンチ","duration":"00:33"},{"exercise":"アームレイズ","duration":"00:33"},{"exercise":"サイドアームレイズ","duration":"00:33"},{"exercise":"三頭筋ディップ","reps":"x13"},{"exercise":"アームサークル（時計回り）","duration":"00:33"},{"exercise":"アームサークル（反時計回り）","duration":"00:33"},{"exercise":"ダイヤモンド・プッシュアップ","reps":"x10"},{"exercise":"プッシュアップ","reps":"x13"},{"exercise":"パンチ","duration":"00:33"},{"exercise":"アームレイズ","duration":"00:33"},{"exercise":"サイドアームレイズ","duration":"00:33"},{"exercise":"三頭筋ディップ","reps":"x13"},{"exercise":"アームサークル（時計回り）","duration":"00:33"},{"exercise":"アームサークル（反時計回り）","duration":"00:33"},{"exercise":"ダイヤモンド・プッシュアップ","reps":"x10"},{"exercise":"プッシュアップ","reps":"x13"},{"exercise":"上腕三頭筋ストレッチ（左）","duration":"00:30"},{"exercise":"大腿四頭筋ストレッチ（左）","duration":"00:30"}] },
    { id: 'arm-3', title: '腕 上級', durationMin: 30, exerciseCount: 28, difficulty: 3, targetArea: '腕', exercises: [{"exercise":"アームレイズ","duration":"00:36"},{"exercise":"サイドアームレイズ","duration":"00:36"},{"exercise":"三頭筋ディップ","reps":"x16"},{"exercise":"アームサークル（時計回り）","duration":"00:36"},{"exercise":"アームサークル（反時計回り）","duration":"00:36"},{"exercise":"ダイヤモンド・プッシュアップ","reps":"x12"},{"exercise":"プッシュアップ","reps":"x16"},{"exercise":"パンチ","duration":"00:36"},{"exercise":"アームレイズ","duration":"00:36"},{"exercise":"サイドアームレイズ","duration":"00:36"},{"exercise":"三頭筋ディップ","reps":"x16"},{"exercise":"アームサークル（時計回り）","duration":"00:36"},{"exercise":"アームサークル（反時計回り）","duration":"00:36"},{"exercise":"ダイヤモンド・プッシュアップ","reps":"x12"},{"exercise":"プッシュアップ","reps":"x16"},{"exercise":"パンチ","duration":"00:36"},{"exercise":"アームレイズ","duration":"00:36"},{"exercise":"サイドアームレイズ","duration":"00:36"},{"exercise":"三頭筋ディップ","reps":"x16"},{"exercise":"アームサークル（時計回り）","duration":"00:36"},{"exercise":"アームサークル（反時計回り）","duration":"00:36"},{"exercise":"ダイヤモンド・プッシュアップ","reps":"x12"},{"exercise":"プッシュアップ","reps":"x16"},{"exercise":"パンチ","duration":"00:36"},{"exercise":"アームレイズ","duration":"00:36"},{"exercise":"サイドアームレイズ","duration":"00:36"},{"exercise":"コブラストレッチ","duration":"00:30"},{"exercise":"コブラストレッチ","duration":"00:30"}] }
  ],
  '胸部': [
    { id: 'chest-1', title: '胸部 初級', durationMin: 12, exerciseCount: 15, difficulty: 1, targetArea: '胸', exercises: [{"exercise":"ジャンピングジャック","duration":"00:30"},{"exercise":"インクライン・プッシュアップ","reps":"x10"},{"exercise":"プッシュアップ","reps":"x8"},{"exercise":"ワイドアーム・プッシュアップ","reps":"x8"},{"exercise":"三頭筋ディップ","reps":"x10"},{"exercise":"ワイドアーム・プッシュアップ","reps":"x6"},{"exercise":"インクライン・プッシュアップ","reps":"x8"},{"exercise":"膝つきプッシュアップ","reps":"x10"},{"exercise":"ジャンピングジャック","duration":"00:30"},{"exercise":"インクライン・プッシュアップ","reps":"x10"},{"exercise":"プッシュアップ","reps":"x8"},{"exercise":"ワイドアーム・プッシュアップ","reps":"x8"},{"exercise":"三頭筋ディップ","reps":"x10"},{"exercise":"胸のストレッチ","duration":"00:30"},{"exercise":"大腿四頭筋ストレッチ（右）","duration":"00:30"}] },
    { id: 'chest-2', title: '胸部 中級', durationMin: 20, exerciseCount: 22, difficulty: 2, targetArea: '胸', exercises: [{"exercise":"ジャンピングジャック","duration":"00:33"},{"exercise":"インクライン・プッシュアップ","reps":"x13"},{"exercise":"プッシュアップ","reps":"x10"},{"exercise":"ワイドアーム・プッシュアップ","reps":"x10"},{"exercise":"三頭筋ディップ","reps":"x13"},{"exercise":"ワイドアーム・プッシュアップ","reps":"x7"},{"exercise":"インクライン・プッシュアップ","reps":"x10"},{"exercise":"膝つきプッシュアップ","reps":"x13"},{"exercise":"ジャンピングジャック","duration":"00:33"},{"exercise":"インクライン・プッシュアップ","reps":"x13"},{"exercise":"プッシュアップ","reps":"x10"},{"exercise":"ワイドアーム・プッシュアップ","reps":"x10"},{"exercise":"三頭筋ディップ","reps":"x13"},{"exercise":"ワイドアーム・プッシュアップ","reps":"x7"},{"exercise":"インクライン・プッシュアップ","reps":"x10"},{"exercise":"膝つきプッシュアップ","reps":"x13"},{"exercise":"ジャンピングジャック","duration":"00:33"},{"exercise":"インクライン・プッシュアップ","reps":"x13"},{"exercise":"プッシュアップ","reps":"x10"},{"exercise":"ワイドアーム・プッシュアップ","reps":"x10"},{"exercise":"上腕三頭筋ストレッチ（右）","duration":"00:30"},{"exercise":"肩のストレッチ","duration":"00:30"}] },
    { id: 'chest-3', title: '胸部 上級', durationMin: 25, exerciseCount: 26, difficulty: 3, targetArea: '胸', exercises: [{"exercise":"ジャンピングジャック","duration":"00:36"},{"exercise":"インクライン・プッシュアップ","reps":"x16"},{"exercise":"プッシュアップ","reps":"x12"},{"exercise":"ワイドアーム・プッシュアップ","reps":"x12"},{"exercise":"三頭筋ディップ","reps":"x16"},{"exercise":"ワイドアーム・プッシュアップ","reps":"x9"},{"exercise":"インクライン・プッシュアップ","reps":"x12"},{"exercise":"膝つきプッシュアップ","reps":"x16"},{"exercise":"ジャンピングジャック","duration":"00:36"},{"exercise":"インクライン・プッシュアップ","reps":"x16"},{"exercise":"プッシュアップ","reps":"x12"},{"exercise":"ワイドアーム・プッシュアップ","reps":"x12"},{"exercise":"三頭筋ディップ","reps":"x16"},{"exercise":"ワイドアーム・プッシュアップ","reps":"x9"},{"exercise":"インクライン・プッシュアップ","reps":"x12"},{"exercise":"膝つきプッシュアップ","reps":"x16"},{"exercise":"ジャンピングジャック","duration":"00:36"},{"exercise":"インクライン・プッシュアップ","reps":"x16"},{"exercise":"プッシュアップ","reps":"x12"},{"exercise":"ワイドアーム・プッシュアップ","reps":"x12"},{"exercise":"三頭筋ディップ","reps":"x16"},{"exercise":"ワイドアーム・プッシュアップ","reps":"x9"},{"exercise":"インクライン・プッシュアップ","reps":"x12"},{"exercise":"膝つきプッシュアップ","reps":"x16"},{"exercise":"肩のストレッチ","duration":"00:30"},{"exercise":"上腕三頭筋ストレッチ（左）","duration":"00:30"}] }
  ],
  '脚': [
    { id: 'leg-1', title: '脚 初級', durationMin: 18, exerciseCount: 20, difficulty: 1, targetArea: '脚', exercises: [{"exercise":"サイド・ホップ","duration":"00:30"},{"exercise":"スクワット","reps":"x12"},{"exercise":"サイドレッグリフト-左","reps":"x12"},{"exercise":"サイドレッグリフト-右","reps":"x12"},{"exercise":"ランジ","reps":"x14"},{"exercise":"カーフレイズ","reps":"x20"},{"exercise":"ドンキーキック-左","reps":"x15"},{"exercise":"ドンキーキック-右","reps":"x15"},{"exercise":"サイド・ホップ","duration":"00:30"},{"exercise":"スクワット","reps":"x12"},{"exercise":"サイドレッグリフト-左","reps":"x12"},{"exercise":"サイドレッグリフト-右","reps":"x12"},{"exercise":"ランジ","reps":"x14"},{"exercise":"カーフレイズ","reps":"x20"},{"exercise":"ドンキーキック-左","reps":"x15"},{"exercise":"ドンキーキック-右","reps":"x15"},{"exercise":"サイド・ホップ","duration":"00:30"},{"exercise":"スクワット","reps":"x12"},{"exercise":"大腿四頭筋ストレッチ（左）","duration":"00:30"},{"exercise":"大腿四頭筋ストレッチ（右）","duration":"00:30"}] },
    { id: 'leg-2', title: '脚 中級', durationMin: 26, exerciseCount: 28, difficulty: 2, targetArea: '脚', exercises: [{"exercise":"サイド・ホップ","duration":"00:33"},{"exercise":"スクワット","reps":"x15"},{"exercise":"サイドレッグリフト-左","reps":"x15"},{"exercise":"サイドレッグリフト-右","reps":"x15"},{"exercise":"ランジ","reps":"x18"},{"exercise":"カーフレイズ","reps":"x26"},{"exercise":"ドンキーキック-左","reps":"x19"},{"exercise":"ドンキーキック-右","reps":"x19"},{"exercise":"サイド・ホップ","duration":"00:33"},{"exercise":"スクワット","reps":"x15"},{"exercise":"サイドレッグリフト-左","reps":"x15"},{"exercise":"サイドレッグリフト-右","reps":"x15"},{"exercise":"ランジ","reps":"x18"},{"exercise":"カーフレイズ","reps":"x26"},{"exercise":"ドンキーキック-左","reps":"x19"},{"exercise":"ドンキーキック-右","reps":"x19"},{"exercise":"サイド・ホップ","duration":"00:33"},{"exercise":"スクワット","reps":"x15"},{"exercise":"サイドレッグリフト-左","reps":"x15"},{"exercise":"サイドレッグリフト-右","reps":"x15"},{"exercise":"ランジ","reps":"x18"},{"exercise":"カーフレイズ","reps":"x26"},{"exercise":"ドンキーキック-左","reps":"x19"},{"exercise":"ドンキーキック-右","reps":"x19"},{"exercise":"サイド・ホップ","duration":"00:33"},{"exercise":"スクワット","reps":"x15"},{"exercise":"肩のストレッチ","duration":"00:30"},{"exercise":"胸のストレッチ","duration":"00:30"}] },
    { id: 'leg-3', title: '脚 上級', durationMin: 35, exerciseCount: 32, difficulty: 3, targetArea: '脚', exercises: [{"exercise":"サイド・ホップ","duration":"00:36"},{"exercise":"スクワット","reps":"x19"},{"exercise":"サイドレッグリフト-左","reps":"x19"},{"exercise":"サイドレッグリフト-右","reps":"x19"},{"exercise":"ランジ","reps":"x22"},{"exercise":"カーフレイズ","reps":"x32"},{"exercise":"ドンキーキック-左","reps":"x24"},{"exercise":"ドンキーキック-右","reps":"x24"},{"exercise":"サイド・ホップ","duration":"00:36"},{"exercise":"スクワット","reps":"x19"},{"exercise":"サイドレッグリフト-左","reps":"x19"},{"exercise":"サイドレッグリフト-右","reps":"x19"},{"exercise":"ランジ","reps":"x22"},{"exercise":"カーフレイズ","reps":"x32"},{"exercise":"ドンキーキック-左","reps":"x24"},{"exercise":"ドンキーキック-右","reps":"x24"},{"exercise":"サイド・ホップ","duration":"00:36"},{"exercise":"スクワット","reps":"x19"},{"exercise":"サイドレッグリフト-左","reps":"x19"},{"exercise":"サイドレッグリフト-右","reps":"x19"},{"exercise":"ランジ","reps":"x22"},{"exercise":"カーフレイズ","reps":"x32"},{"exercise":"ドンキーキック-左","reps":"x24"},{"exercise":"ドンキーキック-右","reps":"x24"},{"exercise":"サイド・ホップ","duration":"00:36"},{"exercise":"スクワット","reps":"x19"},{"exercise":"サイドレッグリフト-左","reps":"x19"},{"exercise":"サイドレッグリフト-右","reps":"x19"},{"exercise":"ランジ","reps":"x22"},{"exercise":"カーフレイズ","reps":"x32"},{"exercise":"胸のストレッチ","duration":"00:30"},{"exercise":"上腕三頭筋ストレッチ（右）","duration":"00:30"}] }
  ],
  '肩と背中': [
    { id: 'shoulder-back-1', title: '肩と背中 初級', durationMin: 14, exerciseCount: 18, difficulty: 1, targetArea: '肩', exercises: [{"exercise":"ジャンピングジャック","duration":"00:30"},{"exercise":"アームレイズ","duration":"00:16"},{"exercise":"ロンボイド（小菱形筋）プル","reps":"x14"},{"exercise":"サイドアームレイズ","duration":"00:16"},{"exercise":"膝つきプッシュアップ","reps":"x14"},{"exercise":"プランク","duration":"00:30"},{"exercise":"アームサークル（時計回り）","duration":"00:30"},{"exercise":"アームサークル（反時計回り）","duration":"00:30"},{"exercise":"ジャンピングジャック","duration":"00:30"},{"exercise":"アームレイズ","duration":"00:16"},{"exercise":"ロンボイド（小菱形筋）プル","reps":"x14"},{"exercise":"サイドアームレイズ","duration":"00:16"},{"exercise":"膝つきプッシュアップ","reps":"x14"},{"exercise":"プランク","duration":"00:30"},{"exercise":"アームサークル（時計回り）","duration":"00:30"},{"exercise":"アームサークル（反時計回り）","duration":"00:30"},{"exercise":"胸のストレッチ","duration":"00:30"},{"exercise":"胸のストレッチ","duration":"00:30"}] },
    { id: 'shoulder-back-2', title: '肩と背中 中級', durationMin: 22, exerciseCount: 24, difficulty: 2, targetArea: '肩', exercises: [{"exercise":"ジャンピングジャック","duration":"00:33"},{"exercise":"アームレイズ","duration":"00:19"},{"exercise":"ロンボイド（小菱形筋）プル","reps":"x18"},{"exercise":"サイドアームレイズ","duration":"00:19"},{"exercise":"膝つきプッシュアップ","reps":"x18"},{"exercise":"プランク","duration":"00:33"},{"exercise":"アームサークル（時計回り）","duration":"00:33"},{"exercise":"アームサークル（反時計回り）","duration":"00:33"},{"exercise":"ジャンピングジャック","duration":"00:33"},{"exercise":"アームレイズ","duration":"00:19"},{"exercise":"ロンボイド（小菱形筋）プル","reps":"x18"},{"exercise":"サイドアームレイズ","duration":"00:19"},{"exercise":"膝つきプッシュアップ","reps":"x18"},{"exercise":"プランク","duration":"00:33"},{"exercise":"アームサークル（時計回り）","duration":"00:33"},{"exercise":"アームサークル（反時計回り）","duration":"00:33"},{"exercise":"ジャンピングジャック","duration":"00:33"},{"exercise":"アームレイズ","duration":"00:19"},{"exercise":"ロンボイド（小菱形筋）プル","reps":"x18"},{"exercise":"サイドアームレイズ","duration":"00:19"},{"exercise":"膝つきプッシュアップ","reps":"x18"},{"exercise":"プランク","duration":"00:33"},{"exercise":"コブラストレッチ","duration":"00:30"},{"exercise":"上腕三頭筋ストレッチ（左）","duration":"00:30"}] },
    { id: 'shoulder-back-3', title: '肩と背中 上級', durationMin: 28, exerciseCount: 30, difficulty: 3, targetArea: '肩', exercises: [{"exercise":"ジャンピングジャック","duration":"00:36"},{"exercise":"アームレイズ","duration":"00:22"},{"exercise":"ロンボイド（小菱形筋）プル","reps":"x22"},{"exercise":"サイドアームレイズ","duration":"00:22"},{"exercise":"膝つきプッシュアップ","reps":"x22"},{"exercise":"プランク","duration":"00:36"},{"exercise":"アームサークル（時計回り）","duration":"00:36"},{"exercise":"アームサークル（反時計回り）","duration":"00:36"},{"exercise":"ジャンピングジャック","duration":"00:36"},{"exercise":"アームレイズ","duration":"00:22"},{"exercise":"ロンボイド（小菱形筋）プル","reps":"x22"},{"exercise":"サイドアームレイズ","duration":"00:22"},{"exercise":"膝つきプッシュアップ","reps":"x22"},{"exercise":"プランク","duration":"00:36"},{"exercise":"アームサークル（時計回り）","duration":"00:36"},{"exercise":"アームサークル（反時計回り）","duration":"00:36"},{"exercise":"ジャンピングジャック","duration":"00:36"},{"exercise":"アームレイズ","duration":"00:22"},{"exercise":"ロンボイド（小菱形筋）プル","reps":"x22"},{"exercise":"サイドアームレイズ","duration":"00:22"},{"exercise":"膝つきプッシュアップ","reps":"x22"},{"exercise":"プランク","duration":"00:36"},{"exercise":"アームサークル（時計回り）","duration":"00:36"},{"exercise":"アームサークル（反時計回り）","duration":"00:36"},{"exercise":"ジャンピングジャック","duration":"00:36"},{"exercise":"アームレイズ","duration":"00:22"},{"exercise":"ロンボイド（小菱形筋）プル","reps":"x22"},{"exercise":"サイドアームレイズ","duration":"00:22"},{"exercise":"胸のストレッチ","duration":"00:30"},{"exercise":"上腕三頭筋ストレッチ（右）","duration":"00:30"}] }
  ]
};
